### ISSUE TITLE
add filter to see only repositories that matter

### ISSUE THREAD

**Issue by ibrahimennafaa** [RonanDrouglazet/GRebase#17]
As a user we should be able to edit a list of shown repos and/or hidden repos. This way when we open grebase we only see the repositories that we work on

**Comment by RonanDrouglazet** [comment]
:+1:  :+1:  :+1:

**Comment by HugoGresse** [comment]
Maybe unchecking repository on the left bar to display only desired repo

**Comment by RonanDrouglazet** [comment]
done :)

**Comment by RonanDrouglazet** [comment]
i will deploy grebase.ebz.io tomorrow, i can't do it from home :)

**Comment by HugoGresse** [comment]
W00t !
