### ISSUE TITLE
We can't manually refresh the status

### ISSUE THREAD

**Issue by stephane-auclair** [RonanDrouglazet/GRebase#8]
For some unknown reason, it happens that the status of some branches is not updated on grebase when the branch is modified.
Aside from understanding why, it would be great to have a way to synchronize the branch without restarting the app.
A "refresh" button under the "recover" would do the trick.

**Comment by RonanDrouglazet** [comment]
done !

**Comment by RonanDrouglazet** [comment]
it's deployed on grebase.ebz.io
